# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
    tags-ignore:           # keep tag pushes out of this workflow
      - 'v*'               # publish.yml handles every v* tag        #1
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  workflow_call:

concurrency:               # ensure only one run per ref
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true                                   #2

permissions:
  contents: read           # checkout / upload-artifact
  pull-requests: write     # annotate lint results on PRs

jobs:
  lint:
    name: Lint & format (pre-commit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"                                       #3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip install -e ".[dev]"

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1                       #4
        with:
          extra_args: --all-files --show-diff-on-failure --color=always

  tests:
    name: Unit tests (pytest)
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]                     #5
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"                                       #3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run pytest
        run: |
          pytest --cov=pattern_local

      #################################################################
      # These two steps make the wheel + sdist available to publish.yml
      #################################################################
      - name: Build wheel & sdist
        run: |
          python -m pip install build                         #6
          python -m build --sdist --wheel --outdir dist/

      - name: Upload distributions
        uses: actions/upload-artifact@v4                      #7
        with:
          name: python-package-distributions
          path: dist/