name: Publish

on:
  workflow_run:
    workflows: ["CI"]       # Runs after your CI workflow
    types:
      - completed           # …when that workflow has finished

jobs:
  publish:
    name: Publish to PyPI
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'v')
    runs-on: ubuntu-latest

    steps:
      # (Optional) Quick debug of incoming values – remove when happy
      - name: Show trigger values
        run: |
          echo "conclusion  = ${{ github.event.workflow_run.conclusion }}"
          echo "head_branch = ${{ github.event.workflow_run.head_branch }}"

      - name: Check out the code from the tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
