name: Publish

on:
  push:
    tags:
      - 'v*'          # semantic-version tags

permissions:
  contents: read      # checkout + download artifacts
  id-token: write     # PyPI Trusted Publishing

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build pytest

      - name: Run test-suite
        run: pytest

      - name: Build wheel + sdist
        run: python -m build --sdist --wheel --outdir dist/

      - name: Upload dists
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1   # Trusted Publishing :contentReference[oaicite:4]{index=4}
