name: Release

on:
  push:
    tags: ['v*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write     # <-- NEW: matches ci.yml needs
  id-token: write

jobs:
  # Re-run your full CI on the tag
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit     # pass repo secrets through

  # Publish only if CI passed
  publish:
    name: Publish to PyPI
    needs: ci            # blocks if CI failed
    runs-on: ubuntu-latest
    steps:
      - name: Build wheel & sdist
        run: python -m build --sdist --wheel --outdir dist/
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
